name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Save current Unix timestamp
      id: timestamp
      run: echo "::set-output name=timestamp::$(date +%s)"

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gwozai/serv:${{ steps.timestamp.outputs.timestamp }}

    - name: Tag the Docker image as latest
      run: docker tag gwozai/serv:${{ steps.timestamp.outputs.timestamp }} ${{ secrets.DOCKER_USERNAME }}/pymessagerabbitmq:latest

    - name: Push to Docker Hub
      run: docker push gwozai/serv:${{ steps.timestamp.outputs.timestamp }}

    - name: Push 'latest' tag to Docker Hub
      run: docker push gwozai/serv:latest